### PR TITLE
data and walk-through for visualisation

### PR DESCRIPTION
**Pull request by christineturner**
The data needed for the visualisation walk-through. `Wales_Constituencies.zip` and `ge_2010_results.csv` are actually used in this walk-through, the others are needed for extensions. The `results` files are from the previous hackathon github and the shapefiles are from https://data.gov.uk/

### CODE REVIEW

**Comment by MrKriss** [comment]
Great work. Can you also add the source Rmd file for the report as well? Also noticed that the link to the public data source doesn't appear to be working.

**Comment by MrKriss** [comment]
Also,  I noted a few recurring typos e.g. constiuency --> constituency,  so worth passing the spellchecker over the Rmd and regenerating output.

**Comment by christineturner** [comment]
I've added the Rmd file and the new version of the html.  I removed that link because I thought it might cause confusion about where to download the data from, so now only the github is linked. Did a spellcheck!

**Comment by MrKriss** [comment]
Combined this visualisation work with the Python ported version. Some changes include:

* Changing the data source to use ONS Open Geography portal, so its easier to use any other data from there as a starting point. Has meant adding a part convert between Northings Eastaings and Lat/Long in degrees. 

* Also now used the `wales_region_data.csv` which is the output from the data manipulation walkthough. It joins up the Press association IDs, and all other ONS codes to a standard name for the region.

**Pull request merged**
